In [1]:
from sklearn.datasets import load_digits

In [2]:
digits=load_digits()


In [3]:
 digits.data.shape

(1797, 64)

In [4]:
digits.target

array([0, 1, 2, ..., 8, 9, 8])

In [5]:
 import matplotlib.pyplot as plt

In [6]:
import numpy as np

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
x_train, x_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.2)


In [9]:
x_train.shape

(1437, 64)

In [10]:
 x_test.shape


(360, 64)

In [11]:
#target value
print(y_train)


[1 5 8 ... 3 9 3]


In [12]:
#first get a list of indices of data
indexList=np.arange(len(x_train))


In [13]:
 print(indexList)

[   0    1    2 ... 1434 1435 1436]


In [14]:
#split training set to labelled and non-labelled
x_labelled=x_train[indexList[:300]]


In [15]:
#split training set to labelled and non-labelled
y_labelled=y_train[indexList[:300]]

In [16]:
nonLabelledIndices=indexList[300:]

In [17]:
 #remove the labels for non labelled indices in training data
y_train_nonlabel = np.copy(y_train)

In [18]:
#setting -1 as non labelled
y_train_nonlabel[nonLabelledIndices] = -1

In [19]:
 from sklearn.semi_supervised import LabelPropagation

In [20]:
 lp=LabelPropagation(gamma=.30)
#gamma is measure of kernel func,


In [21]:
lp.fit(x_train, y_train_nonlabel)

LabelPropagation(gamma=0.3)

In [22]:
 lp.score(x_test,y_test)


0.9583333333333334

In [23]:
#capture labels set by Label Propagataion on the set of non labelled data
y_labelled=lp.transduction_[nonLabelledIndices]

In [24]:
 from sklearn.metrics import confusion_matrix

In [25]:
conf = confusion_matrix(y_train[nonLabelledIndices], y_labelled, labels=lp.classes_)


In [26]:
conf

array([[114,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0, 118,   0,   0,   0,   0,   0,   0,   0,   1],
       [  0,   1, 117,   0,   0,   0,   0,   0,   1,   0],
       [  0,   0,   2, 112,   0,   0,   0,   0,   3,   3],
       [  0,   1,   0,   0, 115,   0,   0,   1,   0,   0],
       [  0,   0,   0,   1,   0, 102,   0,   0,   0,   3],
       [  0,   0,   0,   0,   0,   0,  93,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0, 114,   0,   0],
       [  0,  14,   0,   2,   0,   0,   1,   0,  99,   3],
       [  0,   0,   0,   3,   1,   2,   0,   5,   4, 101]])

In [27]:
from sklearn.semi_supervised import LabelSpreading

In [28]:
ls=LabelSpreading(gamma=0.3)
#gamma is measure of kernel func,

In [29]:
ls.fit(x_train, y_train_nonlabel)


LabelSpreading(gamma=0.3)

In [30]:
 ls.score(x_test,y_test)

0.9611111111111111

In [31]:
 #capture labels set by Label Propagataion on the set of non labelled data
y_labelled=lp.transduction_[nonLabelledIndices]

In [32]:
conf = confusion_matrix(y_train[nonLabelledIndices], y_labelled, labels=lp.classes_)


In [33]:
 conf

array([[114,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0, 118,   0,   0,   0,   0,   0,   0,   0,   1],
       [  0,   1, 117,   0,   0,   0,   0,   0,   1,   0],
       [  0,   0,   2, 112,   0,   0,   0,   0,   3,   3],
       [  0,   1,   0,   0, 115,   0,   0,   1,   0,   0],
       [  0,   0,   0,   1,   0, 102,   0,   0,   0,   3],
       [  0,   0,   0,   0,   0,   0,  93,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0, 114,   0,   0],
       [  0,  14,   0,   2,   0,   0,   1,   0,  99,   3],
       [  0,   0,   0,   3,   1,   2,   0,   5,   4, 101]])