In [ ]:
import numpy as np

In [ ]:
#Make the array [0, 1, 2] with np.array
arr=np.array([0,1,2])

In [ ]:
#checking data type of values
print(arr.dtype)

int64


In [ ]:
 # 1b. Make the array [0, 1, 2] with np.array
 arr=np.arange(0,3)

In [ ]:
#np.arange(starting value, end value+1, step-size)
arr=np.arange(0,10,3)
print(arr)

[0 3 6 9]


In [ ]:
#Make The ELements Zeros
#note that default zeros are of float type
arr=np.zeros(3)

In [ ]:
print(arr)

[0. 0. 0.]


In [ ]:
arr=np.zeros(3,dtype='int64')

In [ ]:
print(arr)

[0 0 0]


In [ ]:
#Make the matrix [[0, 1], [2, 3]] with np.array
arr=np.array([[0,1],[2,3]],dtype='float')

In [ ]:
#Make the matrix [[0, 1], [2, 3]] with np.arange and np.reshape
arr=np.arange(0,4).reshape(2,2)

In [ ]:
print(arr)

[[0 1]
 [2 3]]


In [ ]:
#Print the shape of the matrix from the previous part with .shape
print(arr.shape)

(2, 2)


In [ ]:
#determine type of np.shape output
type=np.shape(arr)

In [ ]:
arr=np.array([0,1,2])
print(np.average(arr))

1.0


In [ ]:
#Add two vectors element-wise
arr1=np.array([0,1,2])
arr2=np.array([3,4,5])

In [ ]:
arr=np.add(arr1,arr2)

In [ ]:
#add works multiple operands
#sum works with only 1array
sum=np.sum(arr)
print(sum)

15


In [ ]:
m=int(input("Enter A number"))

Enter A number27


In [ ]:
print(np.sqrt(m))

5.196152422706632
