In [1]:
#1
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split

In [2]:
import pandas as pd

In [3]:
digits=load_digits()

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
#2
x_train,x_test,y_train,y_test=train_test_split(digits.data,digits.target,test_size=0.25)

In [7]:
#3
import numpy as np
indexList=np.arange(len(x_train))

In [8]:
print(indexList)

[   0    1    2 ... 1344 1345 1346]


In [9]:
#4
x_labelled=x_train[indexList[:300]]

In [10]:
y_labelled=y_train[indexList[:300]]

In [11]:
print(y_labelled)

[0 0 4 9 7 3 9 2 4 1 8 7 7 0 1 4 9 7 6 6 8 5 1 2 7 3 9 3 5 3 1 6 1 8 9 2 0
 7 7 0 8 4 5 3 4 9 5 3 7 6 0 2 7 4 2 9 0 1 5 8 6 6 6 7 7 8 9 0 3 8 6 0 1 6
 5 8 8 7 9 6 1 6 0 7 5 4 4 4 6 3 9 3 8 8 1 3 7 2 1 6 1 6 0 8 2 3 7 2 5 8 1
 9 3 9 1 4 7 8 4 8 2 9 5 5 8 0 3 8 8 6 5 6 8 7 2 7 2 9 3 0 0 2 7 4 5 3 6 9
 4 9 8 9 7 0 9 9 1 1 6 8 4 1 6 2 6 3 0 7 5 2 9 1 4 6 0 6 1 4 9 1 1 6 2 6 1
 4 1 9 1 9 0 0 8 6 5 8 0 2 0 7 9 7 4 2 8 5 7 2 4 4 0 9 9 9 8 1 8 3 7 5 5 8
 6 9 8 1 7 1 6 3 6 7 3 2 4 3 9 0 9 3 3 6 5 9 3 6 7 2 3 7 5 2 8 5 9 1 2 4 5
 4 7 4 1 5 0 4 2 3 8 8 1 1 4 4 7 0 9 9 6 3 5 5 3 3 1 8 5 9 4 2 7 1 5 0 2 3
 9 5 1 5]


In [12]:
#5
nonLabelledIndices=indexList[300:]

In [13]:
print(nonLabelledIndices)

[ 300  301  302 ... 1344 1345 1346]


In [14]:
#6
y_train_nonLabel=np.copy(y_train)

In [15]:
y_train_nonLabel[nonLabelledIndices]=-1

In [16]:
print(y_train_nonLabel)

[ 0  0  4 ... -1 -1 -1]


In [17]:
print(y_train_nonLabel[300:])

[-1 -1 -1 ... -1 -1 -1]


In [18]:
#7
from sklearn.semi_supervised import LabelSpreading

In [19]:
LS=LabelSpreading()

In [20]:
LS.fit(x_train,y_train_nonLabel)

LabelSpreading()

In [22]:
#8
LS.score(x_test,y_test)

/usr/local/lib/python3.7/dist-packages/sklearn/semi_supervised/_label_propagation.py:222: RuntimeWarning: invalid value encountered in true_divide
  probabilities /= normalizer


0.08888888888888889

/usr/local/lib/python3.7/dist-packages/sklearn/semi_supervised/_label_propagation.py:222: RuntimeWarning: invalid value encountered in true_divide
  probabilities /= normalizer


0.08888888888888889

In [23]:
LS1=LabelSpreading(gamma=0.40)

In [25]:
#9
LS1.fit(x_train,y_train_nonLabel)

LabelSpreading(gamma=0.4)

In [26]:
LS1.score(x_test,y_test)

0.9866666666666667

In [29]:
y_labelled=LS.transduction_[nonLabelledIndices]

In [31]:
#10
from sklearn.metrics import confusion_matrix

In [33]:
confMatrix=confusion_matrix(y_train[nonLabelledIndices],y_labelled,labels=LS1.classes_)

In [34]:
print(confMatrix)

[[112   0   0   0   0   0   0   0   0   0]
 [105   1   0   0   0   0   0   0   0   0]
 [106   0   0   0   0   0   0   0   0   0]
 [114   0   0   0   0   0   0   0   0   0]
 [100   0   0   0   0   0   0   0   0   0]
 [115   0   0   0   0   0   0   0   0   0]
 [102   0   0   0   0   0   0   0   0   0]
 [101   0   0   0   0   0   0   0   0   0]
 [ 99   0   0   0   0   0   0   0   0   0]
 [ 92   0   0   0   0   0   0   0   0   0]]
